import * as fs from 'node:fs';

const managers = [
  {
    name: "Brian",
    players: [
      {
        name: "Mario",
        isCaptain: true,
        abilities: [
          "Fireball",
          "Fire Swing",
          "Enlarge",
        ],
        battingStat: 7,
        pitchingStat: 6,
        fieldingStat: 6,
        speedStat: 7,
        chemistry: [
          "Luigi",
          "Peach",
          "Yoshi",
          "Pianta",
          "Noki",
          "Red Mii 1",
          "Red Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Daisy",
        isCaptain: true,
        abilities: [
          "Flower Ball",
          "Flower Swing",
          "Super Dive",
        ],
        battingStat: 6,
        pitchingStat: 7,
        fieldingStat: 8,
        speedStat: 5,
        chemistry: [
          "Peach",
          "Luigi",
          "Birdo",
          "Orange Mii 1",
          "Orange Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Birdo",
        isCaptain: true,
        abilities: [
          "Suction Ball",
          "Cannon Swing",
          "Suction Catch",
        ],
        battingStat: 8,
        pitchingStat: 4,
        fieldingStat: 7,
        speedStat: 5,
        chemistry: [
          "Yoshi",
          "Daisy",
          "Shy Guy",
          "Toadette",
          "Petey Piranha",
          "Pink Mii 1",
          "Pink Mii 2",
        ],
        isDrafted: true,
      },
    ],
  },
  {
    name: "Brian1",
    players: [
      {
        name: "Peach",
        isCaptain: true,
        abilities: [
          "Heart Ball",
          "Heart Swing",
          "Quick Throw",
        ],
        battingStat: 4,
        pitchingStat: 9,
        fieldingStat: 8,
        speedStat: 5,
        chemistry: [
          "Daisy",
          "Mario",
          "Toad",
          "Toadette",
          "Toadsworth",
          "Pink Mii 1",
          "Pink Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Luigi",
        isCaptain: true,
        abilities: [
          "Tornado Ball",
          "Tornado Swing",
          "Super Jump",
        ],
        battingStat: 6,
        pitchingStat: 6,
        fieldingStat: 7,
        speedStat: 7,
        chemistry: [
          "Mario",
          "Daisy",
          "Dark Green Mii 1",
          "Dark Green Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Waluigi",
        isCaptain: true,
        abilities: [
          "Liar Ball",
          "Liar Swing",
          "Quick Throw",
        ],
        battingStat: 4,
        pitchingStat: 8,
        fieldingStat: 8,
        speedStat: 5,
        chemistry: [
          "Wario",
          "Purple Mii 1",
          "Purple Mii 2",
        ],
        isDrafted: true,
      },
    ],
  },
  {
    name: "Brian3",
    players: [
      {
        name: "Yoshi",
        isCaptain: true,
        abilities: [
          "Rainbow Ball",
          "Egg Swing",
          "Tongue Catch",
        ],
        battingStat: 4,
        pitchingStat: 4,
        fieldingStat: 6,
        speedStat: 9,
        chemistry: [
          "Birdo",
          "Mario",
          "Baby Mario",
          "Baby Luigi",
          "Baby Peach",
          "Baby Daisy",
          "Baby DK",
          "Light Green Mii 1",
          "Light Green Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Bowser",
        isCaptain: true,
        abilities: [
          "Killer Ball",
          "Breath Swing",
          "Spin Attack",
        ],
        battingStat: 10,
        pitchingStat: 5,
        fieldingStat: 3,
        speedStat: 3,
        chemistry: [
          "Bowser Jr.",
          "Dry Bones",
          "Bro",
          "Koopa",
          "Paratroopa",
          "Magikoopa",
          "Black Mii 1",
          "Black Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Diddy Kong",
        isCaptain: true,
        abilities: [
          "Banana Ball",
          "Banana Swing",
          "Clamber",
        ],
        battingStat: 4,
        pitchingStat: 5,
        fieldingStat: 8,
        speedStat: 6,
        chemistry: [
          "Donkey Kong",
          "Dixie Kong",
          "Funky Kong",
          "Tiny Kong",
        ],
        isDrafted: true,
      },
    ],
  },
  {
    name: "Brian2",
    players: [
      {
        name: "Wario",
        isCaptain: true,
        abilities: [
          "Phony Ball",
          "Phony Swing",
          "Laser Beam",
        ],
        battingStat: 8,
        pitchingStat: 5,
        fieldingStat: 3,
        speedStat: 4,
        chemistry: [
          "Waluigi",
          "Yellow Mii 1",
          "Yellow Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Donkey Kong",
        isCaptain: true,
        abilities: [
          "Barrel Ball",
          "Barrel Swing",
          "Clamber",
        ],
        battingStat: 9,
        pitchingStat: 6,
        fieldingStat: 3,
        speedStat: 2,
        chemistry: [
          "Diddy Kong",
          "Dixie Kong",
          "Funky Kong",
          "Tiny Kong",
          "Brown Mii 1",
          "Brown Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Bowser Jr.",
        isCaptain: true,
        abilities: [
          "Graffiti Ball",
          "Graffiti Swing",
          "Spin Attack",
        ],
        battingStat: 7,
        pitchingStat: 5,
        fieldingStat: 4,
        speedStat: 7,
        chemistry: [
          "Bowser",
          "Koopa",
          "Bro",
          "Magikoopa",
          "Black Mii 1",
          "Black Mii 2",
        ],
        isDrafted: true,
      },
      {
        name: "Red Yoshi",
        isCaptain: false,
        abilities: [
          "Tongue Catch",
        ],
        battingStat: 4,
        pitchingStat: 3,
        fieldingStat: 4,
        speedStat: 8,
        chemistry: [
          "Birdo",
          "Mario",
          "Baby Mario",
          "Baby Luigi",
          "Baby Peach",
          "Baby Daisy",
          "Baby DK",
          "Red Mii 1",
          "Red Mii 2",
        ],
        isDrafted: true,
      },
    ],
  },
]

const filePath = `../../output/managers-${Date.now()}.json`;
fs.writeFile(filePath, JSON.stringify(managers), (err) => {console.log(`error: ${err}`)});